= Camunda rootbr

_kotlin, Jooby, Camunda, Custom Spin-Gson_

*fast, small, simple*

Концепция


1. запускаем джарник с указанием пути до BPMN
2. есть рест сервис на отправку сообщений процессу (имя сообщения + параметр бизнес-ключ + тело сообщения как json который сохраняется в переменную процесса по названию сообщения) + рест сервис на работу с external-task
3. все сервис таски - external или скрипт (java-delegate, бинов нет)
4. после появление инстранса external-task или user-task - процесс кидает rest-запрос на указанный урл
5. фронт показывает текущие инстрансы процессов. можно выбрать один инстанс по бизнес ключу
6. при выбранном инстансе процесса снизу отображаются переменные процессы, на диаграмме история прохождения по ней + текущие состояние (т. е. для завершенны процессов тоже работает)
7. можно редактировать BPMN с фронта с учетом концепции
8. добавить hikary data pool

http://localhost:8080/h2/h2
jdbc:h2:./camunda-h2-dbs/process-engine;MVCC=TRUE;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE


java -cp /opt/h2/bin/h2*.jar org.h2.tools.Server -tcp -tcpAllowOthers -baseDir ~/tmp/h2dbs -webAllowOthers -webPort 8082

./h2.sh+permission+start
jdbc:h2:tcp://localhost/~/tmp/h2dbs/camunda-h2-dbs/process-engine;MVCC=TRUE;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE

h2 console: http://127.0.1.1:8082
user: sa
password:


* npm install
* npm run bundle
* npm start
https://github.com/rollup/rollup-starter-app/



